Failure # 1 (occurred at 2022-06-17_01-42-01)
[36mray::ImplicitFunc.train()[39m (pid=59684, ip=78.154.136.145, repr=train_and_validate)
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/ray/tune/trainable.py", line 360, in train
    result = self.step()
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/ray/tune/function_runner.py", line 404, in step
    self._report_thread_runner_error(block=True)
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/ray/tune/function_runner.py", line 574, in _report_thread_runner_error
    raise e
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/ray/tune/function_runner.py", line 277, in run
    self._entrypoint()
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/ray/tune/function_runner.py", line 349, in entrypoint
    return self._trainable_func(
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/ray/tune/function_runner.py", line 645, in _trainable_func
    output = fn()
  File "/home/krish/Documents/dogs-vs-cats/py_files/src/search_and_train.py", line 45, in train_and_validate
    torch.save(model.state_dict(), optimizer.state_dict(), path)
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/serialization.py", line 375, in save
    _check_dill_version(pickle_module)
  File "/home/krish/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/serialization.py", line 323, in _check_dill_version
    if pickle_module.__name__ == 'dill':
AttributeError: 'str' object has no attribute '__name__'
